import type { CompanyFormInput } from "../../actions/companies.schema";

export function emptyDefaults(): CompanyFormInput {
	return {
		name: "",
		legalName: "",
		aliases: "",
		description: "",
		tagline: "",
		foundedYear: undefined,
		companyType: "",
		industry: "",
		subIndustry: "",
		companySize: "",
		stockSymbol: "",
		parentCompany: "",
		location: "",
		headquarters: "",
		country: "",
		timezone: "",
		officeLocations: "",
		website: "",
		careersUrl: "",
		linkedinUrl: "",
		twitterUrl: "",
		githubUrl: "",
		glassdoorUrl: "",
		crunchbaseUrl: "",
		blogUrl: "",
		youtubeUrl: "",
		revenue: "",
		fundingStage: "",
		fundingTotal: "",
		valuation: "",
		employeeCount: undefined,
		ceo: "",
		techStack: "",
		benefits: "",
		workCulture: "",
		remotePolicy: "",
		hiringStatus: "",
		glassdoorRating: undefined,
		mainContactName: "",
		mainContactRole: "",
		mainContactEmail: "",
		mainContactPhone: "",
		mainPhone: "",
		mainEmail: "",
		rating: undefined,
		priority: "",
		trackingStatus: "",
		pros: "",
		cons: "",
		notes: "",
	};
}
